[buildPlans.NekoMono]
family = "Neko Mono"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.NekoMono.variants.design]
one = "base-long-top-serif"
four = "semi-open-non-crossing-serifed"
seven = "bend-serifless-crossbar"
nine = "open-contour"
zero = "broken-slash"
capital-c = "unilateral-inward-serifed"
capital-f = "serifed"
capital-h = "top-left-serifed"
capital-k = "curly-top-left-and-bottom-right-serifed"
capital-m = "flat-bottom-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "closed-serifed"
capital-q = "crossing-baseline"
capital-s = "bilateral-inward-serifed"
capital-t = "serifless"
capital-u = "toothless-corner-serifless"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-unilateral-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "diagonal-tailed"
g = "single-storey-earless-corner"
i = "tailed-serifed"
j = "diagonal-tailed-serifless"
k = "straight-top-left-serifed"
l = "diagonal-tailed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
p = "eared-motion-serifed"
q = "top-cut-diagonal-tailed-serifless"
r = "corner-hooked-top-serifed"
s = "unilateral-inward-serifed"
t = "diagonal-tailed"
u = "tailed-serifless"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
y = "cursive-serifless"
z = "straight-serifless"
punctuation-dot = "round"
braille-dot = "round"
asterisk = "turn-penta-high"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
paren = "large-contour"
brace = "curly"
guillemet = "curly"
ampersand = "upper-open"
at = "fourfold-solid-inner"
dollar = "slanted-through"
cent = "through-cap"
percent = "rings-continuous-slash-also-connected"
bar = "natural-slope"
question = "corner"
pilcrow = "low"
micro-sign = "toothed-motion-serifed"
decorative-angle-brackets = "middle"
lig-ltgteq = "flat"
lig-equal-chain = "with-notch"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

  [buildPlans.NekoMono.ligations]
  inherits = "haskell"

[buildPlans.NekoMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.NekoMono.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.NekoMono.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.NekoMono.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.NekoMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.NekoMono.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
